services:
  - type: web
    name: tiktok-bot
    env: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER_URL
        sync: false
